name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run tests
      run: |
        pytest -v --cov=app tests/
      env:
        DB_SERVER: ${{ secrets.TEST_DB_SERVER }}
        DB_NAME: ${{ secrets.TEST_DB_NAME }}
        DB_DRIVER: ${{ secrets.DB_DRIVER }}
        DB_TRUSTED_CONNECTION: ${{ secrets.DB_TRUSTED_CONNECTION }}
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t swarm-app .
    
    - name: Run Docker container
      run: |
        docker run -d -p 8501:8501 \
          -e DB_SERVER=${{ secrets.DB_SERVER }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          -e DB_DRIVER=${{ secrets.DB_DRIVER }} \
          -e DB_TRUSTED_CONNECTION=${{ secrets.DB_TRUSTED_CONNECTION }} \
          swarm-app 